name: Update README with Top Langs Stats

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:  # Adiciona a opção de rodar manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        
      - name: Fetch all repos and get languages
        run: |
          # Defina o seu nome de usuário
          USERNAME="SilasReuel"
          
          # Crie uma variável para o token
          TOKEN="${{ secrets.GH_TOKEN }}"

          # Faça a requisição à API do GitHub para pegar todos os repositórios
          repos=$(curl -s -H "Authorization: token $TOKEN" \
               "https://api.github.com/users/$USERNAME/repos?per_page=100" | \
               jq -r '.[].name')

          # Variável para armazenar as linguagens
          LANGUAGES=""

          # Loop pelos repositórios para pegar as linguagens
          for repo in $repos; do
            echo "Verificando repositório: $repo"  # Adiciona log para depurar o nome do repositório

            lang=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$USERNAME/$repo/languages" | \
              jq -r 'to_entries | map(.key) | .[]')

            # Adiciona as linguagens à variável
            LANGUAGES="$LANGUAGES,$lang"
          done

          # Remova a primeira vírgula
          LANGUAGES=$(echo $LANGUAGES | sed 's/^,//')

          # Crie a URL com as linguagens coletadas
          URL="https://github-readme-stats.vercel.app/api/top-langs/?username=$USERNAME&langs_count=10&layout=compact&hide=$LANGUAGES"

          # Baixe a imagem das linguagens
          curl -o readme_image.png $URL
          
      - name: Update README
        run: |
          # Adicionar ou atualizar a imagem no README (não substituir todo o conteúdo)
          # Caminho da imagem
          IMAGE_URL="https://raw.githubusercontent.com/SilasReuel/development/main/readme_image.png"

          # Substituir o conteúdo entre os marcadores no README.md
          sed -i '/<!-- TOP_LANGS_START -->/,/<!-- TOP_LANGS_END -->/c\<!-- TOP_LANGS_START -->\n![]('"$IMAGE_URL"')\n<!-- TOP_LANGS_END -->' README.md
          
      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md
          git commit -m "Atualizando estatísticas de linguagens"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
