name: Update README with Top Langs Stats

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch all repos and get languages
        run: |
          USERNAME="SilasReuel"
          TOKEN="${{ secrets.GH_TOKEN }}"

          # Obter lista de repositórios
          response=$(curl -s -H "Authorization: token $TOKEN" \
               "https://api.github.com/users/$USERNAME/repos?per_page=100")

          # Verifica se há erro na resposta da API
          if echo "$response" | jq -e 'has("message")' > /dev/null; then
            echo "Erro da API do GitHub: $(echo "$response" | jq -r '.message')"
            exit 1
          fi

          # Extrair nomes dos repositórios
          repos=$(echo "$response" | jq -r '.[] | .name')

          # Coletar linguagens usadas
          LANGUAGES=""
          for repo in $repos; do
            echo "Verificando repositório: $repo"
            lang=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$USERNAME/$repo/languages" | \
              jq -r 'to_entries | map(.key) | .[]' || echo "")
            LANGUAGES="$LANGUAGES,$lang"
          done

          # Limpar lista de linguagens
          LANGUAGES=$(echo $LANGUAGES | sed 's/^,//')

          # Criar URL da imagem
          URL="https://github-readme-stats.vercel.app/api/top-langs/?username=$USERNAME&langs_count=10&layout=compact&hide=$LANGUAGES"

          # Baixar a imagem
          curl -o readme_image.png $URL

      - name: Check if image was downloaded
        run: |
          if [ ! -s readme_image.png ]; then
            echo "Erro: A imagem não foi baixada corretamente!"
            exit 1
          fi

      - name: Update README
        run: |
          # URL correta da imagem
          IMAGE_URL="https://raw.githubusercontent.com/SilasReuel/SilasReuel/main/readme_image.png"

          # Substituir corretamente no README.md dentro dos marcadores
          sed -i '/<!-- TOP_LANGS_START -->/,/<!-- TOP_LANGS_END -->/c\<!-- TOP_LANGS_START -->\n![Top Langs]('"$IMAGE_URL"')\n<!-- TOP_LANGS_END -->' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md readme_image.png
          git commit -m "Atualizando estatísticas de linguagens" || echo "Nenhuma alteração para commitar"
          git push origin main  # Mudado para `main`
        env:
          GH_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}
