name: Update README with Top Langs Stats

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch:  # Permite execução manual

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Fetch all repos and get languages
        run: |
          # Defina o seu nome de usuário
          USERNAME="SilasReuel"
          
          # Crie uma variável para o token
          TOKEN="${{ secrets.GH_PERSONAL_TOKEN }}"  # Usando o PAT para evitar problemas de permissão

          # Obter todos os repositórios do usuário via API do GitHub
          repos=$(curl -s -H "Authorization: token $TOKEN" \
               "https://api.github.com/users/$USERNAME/repos?per_page=100" | \
               jq -r '.[].name')

          # Variável para armazenar as linguagens
          LANGUAGES=""

          # Loop pelos repositórios para coletar as linguagens
          for repo in $repos; do
            echo "Verificando repositório: $repo"

            lang=$(curl -s -H "Authorization: token $TOKEN" \
              "https://api.github.com/repos/$USERNAME/$repo/languages" | \
              jq -r 'to_entries | map(.key) | .[]')

            # Adiciona as linguagens à variável
            LANGUAGES="$LANGUAGES,$lang"
          done

          # Remover a primeira vírgula
          LANGUAGES=$(echo $LANGUAGES | sed 's/^,//')

          # Criar a URL com as linguagens coletadas
          URL="https://github-readme-stats.vercel.app/api/top-langs/?username=$USERNAME&langs_count=10&layout=compact&hide=$LANGUAGES"

          # Baixar a imagem das linguagens
          curl -o readme_image.png $URL
          
      - name: Update README
        run: |
          # Caminho da imagem
          IMAGE_TAG="![Top Langs](./readme_image.png)"

          # Substituir o conteúdo entre os marcadores no README.md
          sed -i '/<!-- TOP_LANGS_START -->/,/<!-- TOP_LANGS_END -->/c\<!-- TOP_LANGS_START -->\n'"$IMAGE_TAG"'\n<!-- TOP_LANGS_END -->' README.md

      - name: Commit and Push Changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add README.md readme_image.png
          git commit -m "Atualizando estatísticas de linguagens"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GH_PERSONAL_TOKEN }}  # Alterado para o PAT
